[package]
name = "relp-num"
version = "0.2.0"
authors = ["Bram van den Heuvel <bram@vandenheuvel.online>"]
edition = "2024"
rust-version = "1.97"
description = "Number types for the relp crate"
repository = "https://github.com/vandenheuvel/relp-num"
license = "GPL-3.0-only"

keywords = ["relp", "exact", "precision", "number", "rational"]
categories = ["algorithms", "science"]

[dependencies]
num-traits = "0.2.7"
gcd = "2.0"
smallvec = { version = "1.6.1", features = ["const_generics"] }
index-utils = "2.3"

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "criterion"
harness = false
path = "benches/criterion/mod.rs"
